### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by minhnimble** [baocntt2602/survey#13]
Hello Bao 👋 , thank you for your effort on the code submission. I am Mike, Engineering Lead at Nimble, and I am happy to be the reviewer for our code review session. At the same time, I would truly appreciate your understanding on the lengthy waiting time due to our huge load of code review submissions. 🙏

Now, regarding the code review process, since I would like to know more about your decisions, I will create issues in some areas where there could be more improvements regarding your submission. It is also aware that solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by minhnimble** [comment]
Hi, Bao 👋

For your information, I just complete the 1st round of review now. Please go ahead and provide your feedback on all the proposed issues. If you have any further inquiry, please don't hesitate to communicate them here.

Have a great day!

**Comment by baocntt2602** [comment]
Hi anh,
Thank you for spending time reviewing my submission
I am looking into every issue and I will get back to you as soon as I have any of them resolved.
Good night anh!

**Comment by minhnimble** [comment]
Good morning Bao 👋, just a friendly reminder that don't forget to merge the PR to the `main` branch if you deemed your PR changes are ready for review. 😉

**Comment by baocntt2602** [comment]
Sure anh, thank you for the reminder

**Comment by baocntt2602** [comment]
Hi anh @minhnimble, I've just merged the PR to resolve issue #16 and please consider it as my last PR for this round of the review as well.
I spent my very last annual leave days to finalize the assignment and resolve the issues so this time I ask for your understanding and I do wish that this may not affect the overall result of my application
In the meantime, I am still available to discuss and answer if you have any further questions or concern
Thank you very much anh!

**Comment by minhnimble** [comment]
Good afternoon Bao ☀️

As of this point, this code challenge review session has concluded, and thus, no more submissions will be needed from your end. For the next step, you will hear from the Talent Acquisition team about the decision as soon as it is available. Thanks for your time, and I wish you all the best! 🍀
