### ISSUE TITLE
[Concern] Secrets managment

### ISSUE THREAD

**Issue by minhnimble** [baocntt2602/survey#14]
Right now, the client's id and secret are exposed in both plaintext and logged into git versioning: 
https://github.com/baocntt2602/survey/blob/f4ba36619f2d92808c6f861e8b4b38a21b2430d7/secrets.defaults.properties#L4-L5

This is a bad security practice that we should avoid at all cost. Your speed of submission is appreciated, but as a reminder, we would also love to see development driven with the least compromise, too.

**Comment by baocntt2602** [comment]
You are correct, It was my terrible mistake when I attempted to test my network module by adding credentials right into this file but forgot to remove them.
These kinds of credentials should be stored in `local.properties` file to run the project locally,
or When we apply CI/CD to make a distribution build to App Center or Google Play Console, we can store them in action secrect (github action), credentials (jenkin), ... 
I also noticed this issue a long time ago but as you said, it's already logged into the git history. 
Anyway, I resolved this issue by simply deleting them in this [PR](https://github.com/baocntt2602/survey/pull/19)
