### ISSUE TITLE
[Concern] The shimmer loading view doesn't match with design 

### ISSUE THREAD

**Issue by minhnimble** [baocntt2602/survey#17]
## Why

The application needs to show the initial shimmer loading view with animation after first entering the app with a valid logged in session like design. Currently, the loading only shows the animated top components (title, circle avatar) with incorrectly horizontal length compared to the design:

https://github.com/baocntt2602/survey/assets/70877098/d6140f81-1291-4ddd-99c2-1df2d0fa01e3

## Acceptance Criteria
- The skeleton loading view needs to look like the following design with sufficient animated components:

<img src="https://user-images.githubusercontent.com/70877098/159680292-df2c41e9-49af-4a0f-bc86-2b71cfe69433.png" width="300">

**Comment by baocntt2602** [comment]
The first approach that I could think of when implementing this shimmer loading is to create a dedicated composable view just to contain all the shimmer composable, but then I think that way would make code duplicated while we can use just one composable to show shimmer and display the data with a customized shimmer Modifier, then in future, if we need to implement shimmer loading in other screens, we don't need to create another composable as well.
But this way clearly has 1 disadvantage as you pointed out above.
I will be fixing this by applying the first approach.

**Comment by baocntt2602** [comment]
I improved the shimmer loading in this [PR](https://github.com/baocntt2602/survey/pull/22), which I also attached a demo video for the inspection
